In [29]:
import numpy as np
import os
from utils.transformation_sixd import smplx_to_6d, sixd_to_smplx

In [2]:
np.load("mydataset/gait_011/20251107_c1_a1_Take1/split_subjects/0/keypoints_3d/smpl-keypoints_cut.npy").shape

(63, 25, 5)

In [24]:
# openpose stats

root="mydataset"
i=0

for gait in os.listdir(root):
    gait_path=os.path.join(root,gait)
    lengths=[]
    x_coords=[]
    y_coords=[]
    z_coords=[]
    for take in os.listdir(gait_path):
        sequence_path=os.path.join(gait_path,take,"split_subjects/0/keypoints_3d/smpl-keypoints-3d_cut.npy")
        data=np.load(sequence_path)
        #print(data[0,0,:3])
        x_coords.append(np.max(data[:,i,0]))
        x_coords.append(np.min(data[:,i,0]))
        y_coords.append(np.max(data[:,i,1]))
        y_coords.append(np.min(data[:,i,1]))
        z_coords.append(np.max(data[:,i,2]))
        z_coords.append(np.min(data[:,i,2]))
        lengths.append(data.shape[0])
    #print(gait,lengths)
    #print(gait,max(lengths),min(lengths))
    print(gait,max(x_coords), max(y_coords), max(z_coords))
    print(gait,min(x_coords), min(y_coords), min(z_coords))



gait_011 0.6284517597699179 2.0029172129390833 1.3952250170717944
gait_011 -0.7750142675976146 0.8451797277411195 -1.3823186344485985
gait_052 0.6873598366739131 1.3811971815038944 1.3715027981082446
gait_052 -0.5689291981268328 0.6905244357660919 -1.587894619501878
gait_133 0.6797287888115038 1.3580241516581066 1.2743402502498604
gait_133 -0.5748530266666068 0.6685180810125675 -1.245905123307373
gait_390 0.6537345367513068 1.770363017621138 1.5007060372875203
gait_390 -0.7331151220609871 0.9015451367698802 -1.5480681034754027
gait_520 0.8136788771561108 1.9756957064961131 1.441245313114038
gait_520 -0.9340374284130158 0.9158549456943204 -1.3589324282998692
gait_682 0.7335839279710116 1.643421970459998 1.2935543483366663
gait_682 -0.7076894917349508 0.8032472265013743 -1.3999003367922145
gait_700 0.5205990897939401 1.7512868909436934 1.3484675758030802
gait_700 -0.5342748648546899 0.904795552584682 -1.3082068736744268
gait_740 0.6544128398228447 1.7963255220642584 1.367443488189584
gai

In [ ]:
# 6d stats

root="mydataset"
i=0

for gait in os.listdir(root):
    gait_path=os.path.join(root,gait)
    lengths=[]
    x_coords=[]
    y_coords=[]
    z_coords=[]
    motion_shapes_max=[]
    motion_shapes_min=[]
    for take in os.listdir(gait_path):
        sequence_path=os.path.join(gait_path,take,"split_subjects/0/fit-smplx/smplx-params_cut.npz")
        data=smplx_to_6d(sequence_path)
        transl=data['transl']
        x_coords.append(np.max(transl[:,0]))
        x_coords.append(np.min(transl[:,0]))
        y_coords.append(np.max(transl[:,1]))
        y_coords.append(np.min(transl[:,1]))
        z_coords.append(np.max(transl[:,2]))
        z_coords.append(np.min(transl[:,2]))
        motion=data['motion_6d']
        motion_shapes_max.append(np.max(motion))
        motion_shapes_min.append(np.min(motion))
    print(gait,max(x_coords), max(y_coords), max(z_coords))
    print(gait,min(x_coords), min(y_coords), min(z_coords))
    print(gait,max(motion_shapes_max), min(motion_shapes_min))
    print("==============")


[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
gait_011 0.09374523 0.055384636 0.0
gait_011 -1.1350725 -0.42987418 -2.4117427
gait_011 1.0 -0.99997354
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
gait_052 0.12798023 0.051422477 0.053468466
gait_052 -1.1897724 -0.08875799 -2.8032281
gait_052 1.0 -0.9999949
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
gait_133 0.16646948 0.053118944 0.06509054
gait_133 -1.0673